version: '3'
services:
  app:
    image: debmalyasen/seoearningspace-new
    ports:
      - 80:3000
    networks:
      - web
  nginx:
    image: nginx
    ports:
      - 80:3000
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - web
networks:
  web:
    driver: bridge