import AuthProvider from '@/context/AuthProvider';
import './globals.css'
import { SessionProvider } from 'next-auth/react';
import { Toaster } from '@/components/ui/toaster';
import Nav from '@/components/Nav';
export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
        <AuthProvider>
      <body>
          <Nav/>
        {children}
        <Toaster/>
      </body>
        </AuthProvider>        
    </html>
  )
}