import AuthProvider from '@src/context/AuthProvider';
import './globals.css'
import { SessionProvider } from 'next-auth/react';
import { Toaster } from '@src/components/ui/toaster';
import Nav from '@src/components/Nav';
export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
        <AuthProvider>
        <body className="h-screen flex">
          {/* Navbar (left side) */}
          <Nav />
          
          {/* Main Content (right side) */}
          <div className="flex-1 overflow-auto">
            {children}
          </div>

          {/* Toaster for notifications */}
          <Toaster />
        </body>
        </AuthProvider>        
    </html>
  )
}